# Задание 1

Задайте матрицу А=$\left( \begin{matrix}
   3.25 & -1.07 & 2.34  \\
   10.1 & 0.25 & -4.78  \\
   5.04 & -7.79 & 3.31  \\
\end{matrix} \right)$


In [2]:
import numpy as np

A = np.array([[3.25, -1.07, 2.34],[10.1, 0.25, -4.78],[5.04, -7.79, 3.31]
])

print("Matrix A:")
print(A)

Matrix A:
[[ 3.25 -1.07  2.34]
 [10.1   0.25 -4.78]
 [ 5.04 -7.79  3.31]]


# Задание 2

Найти матрицу, обратную к A.

In [ ]:
A_inv = np.linalg.inv(A)

print(A_inv)

# Задание 3

Сгенерируйте матрицу В размером 3х3 со случайными элементами, равномерно распределенными на интервале от 0 до 1. Выполнить операцию умножения матриц A и B, а затем транспонировать получившуюся матрицу.

In [3]:
B = np.random.rand(3, 3)
print(B)

C = np.dot(A, B)
print(C)

C_T = C.T
print("C (C_T):")
print(C_T)

[[0.53969345 0.62217526 0.8599953 ]
 [0.55260598 0.61839172 0.22265041]
 [0.01293389 0.35616443 0.36127646]]

Matrix C (A * B):
[[ 1.19298063  2.19381522  3.40213571]
 [ 5.52723136  4.73610205  7.01471371]
 [-1.54193441 -0.50260392  3.7957547 ]]

Transposed Matrix C (C_T):
[[ 1.19298063  5.52723136 -1.54193441]
 [ 2.19381522  4.73610205 -0.50260392]
 [ 3.40213571  7.01471371  3.7957547 ]]


# Задание 4

Нормализовать элементы заданного одномерного массива таким образом, чтобы значения лежали в диапазоне [0, 1].

In [4]:
arr = np.array([1, 5, 10, 15, 20])

min_val = np.min(arr)
max_val = np.max(arr)

if max_val == min_val:
    normalized_arr = [0]*len(arr)
else:
    normalized_arr = (arr - min_val) / (max_val - min_val)

print(normalized_arr)

[0.         0.21052632 0.47368421 0.73684211 1.        ]


# Задание 5

Расположите элементы  матрицы А по возрастанию (по столбцам), определите максимальный и минимальный элементы  матрицы В, вычислите определитель матрицы В.

In [ ]:
import numpy as np

A_col = np.sort(A, axis=0)
print(A_sorted_by_columns)

max_B = np.max(B)
print(f"\n max of B: {max_B}")

min_B = np.min(B)
print(f" min of B: {min_B}")

det_B = np.linalg.det(B)
print(f"Определитель: {det_B}")

# Задание 6

Для двумерного массива размерностью 4×4 поменять местами первую строку и последнюю строки массива.

In [7]:
arr = np.random.randint(0, 10, size=(4, 4))
print(arr)

arr[[0, 3]] = arr[[3, 0]]

print(arr)

[[4 5 2 2]
 [9 7 2 8]
 [1 6 6 9]
 [1 6 4 9]]

Array after swapping first and last rows:
[[4 5 2 1]
 [9 7 2 8]
 [1 6 6 9]
 [1 6 4 9]]


# Задание 7

Создать массив случайных вещественных чисел размером 5х5, используя функцию numpy.random.rand(). Затем вывести среднее значение элементов массива.

In [9]:
arr = np.random.rand(5, 5)
print(arr)

mean_val = arr.mean()
print(f"\n mean: {mean_val}")

[[0.70807456 0.2778834  0.41257444 0.73975206 0.11700191]
 [0.38746473 0.90030009 0.54259951 0.7724927  0.11000479]
 [0.0427112  0.06938621 0.21358367 0.31462968 0.199831  ]
 [0.90631414 0.1655883  0.87254262 0.27052539 0.20430854]
 [0.97892256 0.64883027 0.25564154 0.90716718 0.72809295]]

 mean: 0.4698489377759875


# Задание 8

Задан вектор v длины 5. Рассчитайте евклидову норму этого вектора (также называемую L2-нормой).

In [10]:
arr = np.random.rand(5)
print(np.linalg.norm(arr))

1.5679111232669556


# Задание 9

Создайте два массива одинаковой формы: первый состоит из четных чисел от 2 до 10, второй — из квадратов этих же чисел. Соедините оба массива горизонтально (по столбцам).

In [12]:

arr1 = np.arange(2, 11, 2)
print(arr1)

arr2 = arr1**2

arr1_2d = arr1.reshape(-1, 1)
arr2_2d = arr2.reshape(-1, 1)

combined_arr = np.hstack((arr1_2d, arr2_2d))
print("\nResult\n")
print(combined_arr)

[ 2  4  6  8 10]

Result

[[  2   4]
 [  4  16]
 [  6  36]
 [  8  64]
 [ 10 100]]


# Задание 10

Задать массив С, используя операцию индексации и функцию ones:
$\left( \begin{matrix}
   1  \\
   1  \\
   -2.2  \\
   1   \\   
\end{matrix} \right)$

In [16]:
C = np.ones(4)
C[2] = -2.2

print("C:")
print(C)

C:
[ 1.   1.  -2.2  1. ]


# Задание 11

Для двух векторов:
С и b= {0.6; 1.2; -1.8, 1.05} найти меру косинусного сходства.


In [17]:
b = np.array([0.6, 1.2, -1.8, 1.05])

cos_sim = np.dot(C,b) / (np.linalg.norm(b) * np.linalg.norm(C))
print(cos_sim)

0.9813332136844151
