<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#PyTorch.-Основы:-синтаксис,-torch.cuda-и-torch.autograd" data-toc-modified-id="PyTorch.-Основы:-синтаксис,-torch.cuda-и-torch.autograd-1"><span class="toc-item-num">1&nbsp;&nbsp;</span><b>PyTorch. Основы: синтаксис, torch.cuda и torch.autograd</b></a></span><ul class="toc-item"><li><span><a href="#Задача-1" data-toc-modified-id="Задача-1-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Задача 1</a></span></li><li><span><a href="#Задача-2" data-toc-modified-id="Задача-2-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Задача 2</a></span></li><li><span><a href="#Задача-3" data-toc-modified-id="Задача-3-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Задача 3</a></span></li><li><span><a href="#Задача-4" data-toc-modified-id="Задача-4-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Задача 4</a></span></li><li><span><a href="#Задача-5" data-toc-modified-id="Задача-5-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Задача 5</a></span></li></ul></li></ul></div>

---

<h2 style="text-align: center;"><b>PyTorch. Основы: синтаксис, torch.cuda и torch.autograd</b></h2>

<p style="align: center;"><img src="https://raw.githubusercontent.com/pytorch/pytorch/master/docs/source/_static/img/pytorch-logo-dark.png", width=400, height=300></p>

---

In [ ]:
import torch
import matplotlib.pyplot as plt

### Задача 1

1). Создайте два вещественных тензора: `a` размером (3, 4) и `b` размером (12,)   
2). Создайте тензор `c`, являющийся тензором `b`, но размера (2, 2, 3)  
3). Выведите первый столбец матрицы `a` с помощью индексации

In [1]:
a = torch.randn(3, 4)
b = torch.randn(12)
c = b.reshape(2, 2, 3)

print("Первый столбец a:")
print(a[:, 0])
print("\nПервая строка a:")
print(a[0, :])

print("\na:")
print(a)

print("\nb:")
print(b)

print("\nc:")
print(c)

### Задача 2

1). Создайте два вещественных тензора: `a` размером (5, 2) и `b` размером (1,10)   
2). Создайте тензор `c`, являющийся тензором `b`, но размера (5, 2)  
3). Произведите все арифметические операции с тензорами `a` и `c`

In [2]:
a = torch.randn(5, 2)
b = torch.randn(1, 10)
c = b.reshape(5, 2)

print("a:")
print(a)

print("\nc:")
print(c)

print("\na + c:")
print(a + c)

print("\na - c:")
print(a - c)

print("\na * c:")
print(a * c)

print("\na / c:")
print(a / c)

print("\na ** c:")
print(a ** c)

a:
tensor([[ 0.1285,  0.3776],
        [ 0.7601, -0.9602],
        [-0.1181,  0.6660],
        [-0.4551, -1.4471],
        [-2.5660, -1.1447]])

c:
tensor([[-0.4611,  0.8810],
        [-1.1622,  0.6855],
        [ 1.4858,  0.1186],
        [ 0.0852, -0.3498],
        [ 0.8924, -1.8769]])

a + c:
tensor([[-0.3327,  1.2585],
        [-0.4021, -0.2747],
        [ 1.3677,  0.7846],
        [-0.3699, -1.7969],
        [-1.6736, -3.0216]])

a - c:
tensor([[ 0.5896, -0.5034],
        [ 1.9222, -1.6457],
        [-1.6039,  0.5474],
        [-0.5403, -1.0973],
        [-3.4584,  0.7322]])

a * c:
tensor([[-0.0592,  0.3326],
        [-0.8833, -0.6583],
        [-0.1755,  0.0790],
        [-0.0388,  0.5062],
        [-2.2899,  2.1485]])

a / c:
tensor([[-0.2786,  0.4286],
        [-0.6540, -1.4008],
        [-0.0795,  5.6154],
        [-5.3393,  4.1372],
        [-2.8754,  0.6099]])

a ** c:
tensor([[2.5761, 0.4240],
        [1.3755,    nan],
        [   nan, 0.9529],
        [   nan,    nan],
  

### Задача 3

1). Создайте тензор *целых чисел* `images` размерности (100, 200, 200, 3) (можно интерпретировать это как 100 картинок размера 200х200 с тремя цветовыми каналами, то есть 100 цветных изображений 200х200). Заполните его нулями  

2). Сделайте так, чтобы у $i$-ой по порядку картинки была нарисована белая полоса толщиной два пикселя в строках, которые соответствуют номеру картинки. Например, у 3-ей по порядку картинки белая полоска будет занимать 6 и 7 строки, у 99 -- 198 и 199. Сделать белую строку можно, записав в ячейки тензора число 255 (по всем трём каналам). Выведите пару примеров с помощоью `pylot`  

3). Посчитайте среднее тензора `images` по 1-ой оси (по сути - средняя картинка), умножьте полученный тензор на 70. Нарисуйте с помощью `pyplot`, должна получиться серая картинка (при взятии среднего нужно привести тензор к float с помощью `.float()`, при отрисовке обратно к int с помощью `.int()`)

In [7]:
images = torch.zeros((100, 200, 200, 3), dtype=torch.int32)
idx = torch.arange(100)
rows = 2* idx

images[idx, rows, :, :] = 255
images[idx, rows+1, :, :] = 255

mean_image = images.float().mean(dim=0) * 70
mean_image = mean_image.int()

plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.imshow(images[3].numpy())
plt.title("Image 3")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(images[50].numpy())
plt.title("Image 50")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(mean_image.numpy())
plt.title("Mean image * 70")
plt.axis("off")

plt.show()


Epoch    0 | Loss = 1.0966 | Accuracy = 0.3433
Epoch  200 | Loss = 0.0992 | Accuracy = 0.9700
Epoch  400 | Loss = 0.0484 | Accuracy = 0.9867


KeyboardInterrupt: 

### Задача 4

Перейдите на Google Colaboratory, чтобы работать с GPU. Загрузите туда этот ноутбук (Upload notebook)
В Colab нажмите в меню сверху: Runtime -> Change Runtime Type -> GPU, где изначально стоит None
Объявите тензор a размера (2, 3, 4) и тензор b размера (1, 8, 3) на GPU, иницилизируйте их случайно равномерно (.uniform_())
Затем измените форму тензора b, чтобы она совпадала с формой тензора a, получите тензор c
Переместите c на CPU, переместите a на CPU
Оберните их в Variable()
Объявите тензор L = torch.mean((c - a) ** 2) и посчитайте градиент L по c ( то есть  ∂𝐿∂𝑐)

Выведите градиент L по c

In [6]:
from torch.autograd import Variable

print(torch.cuda.is_available())
device = torch.device("cude")

a = torch.empty((2, 3, 4), device=device).uniform_()
b = torch.empty((1,8,3), device=device).uniform_()
c = b.reshape(2, 3, 4)

a = a.cpu()
c = c.cpu()
a = Variable(a)
c = Variable(c, requires_grad=True)

L = torch.mean((c-a)**2)
L.backward()

print("Тензор a:")
print(a)

print("\nТензор c:")
print(c)

print("\nL:")
print(L)

print("\nГрадиент dL/dc:")
print(c.grad)

False


RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, maia, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: cude

### Задача 5

Доработайте многослойную нейронную сеть из файла "4_3 mlp pytorch tasks".

In [8]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

# создаём данные для 3 классов
N = 100   # количество точек в каждом классе
D = 2     # количество признаков
K = 3     # количество классов

# массив для координат точек
X = np.zeros((N * K, D))

# массив для номеров классов
y = np.zeros(N * K, dtype=np.int64)

# генерируем 3 "спиральных" класса
for j in range(K):

    # индексы объектов текущего класса
    ix = range(N * j, N * (j + 1))

    # расстояние от центра
    r = np.linspace(0.0, 1, N)

    # угол + небольшой шум
    t = np.linspace(j * 4, (j + 1) * 4, N) + np.random.randn(N) * 0.2

    # записываем координаты
    X[ix] = np.c_[r * np.sin(t), r * np.cos(t)]

    # записываем номер класса
    y[ix] = j

# переводим данные в тензоры PyTorch
X_tensor = torch.FloatTensor(X)
y_tensor = torch.LongTensor(y)

# создаём нейросеть
model = nn.Sequential(
    nn.Linear(2, 128),
    nn.ReLU(),
    nn.Dropout(0.2),

    nn.Linear(128, 128),
    nn.ReLU(),
    nn.Dropout(0.2),

    nn.Linear(128, 64),
    nn.ReLU(),

    nn.Linear(64, 3)
)

# функция ошибки
loss_fn = nn.CrossEntropyLoss()

# оптимизатор
optimizer = optim.Adam(model.parameters(), lr=0.001)

# обучение
epochs = 2000

for epoch in range(epochs):

    optimizer.zero_grad()

    predictions = model(X_tensor)

    loss = loss_fn(predictions, y_tensor)

    loss.backward()

    optimizer.step()

    if epoch % 200 == 0:
        predicted_classes = torch.argmax(predictions, dim=1)
        accuracy = (predicted_classes == y_tensor).float().mean()

        print(
            f"Epoch {epoch:4d} | "
            f"Loss = {loss.item():.4f} | "
            f"Accuracy = {accuracy.item():.4f}"
        )

# итоговая точность
model.eval()

with torch.no_grad():
    final_predictions = model(X_tensor)
    final_classes = torch.argmax(final_predictions, dim=1)
    final_accuracy = (final_classes == y_tensor).float().mean()

print(f"\nFinal accuracy: {final_accuracy.item():.4f}")

# строим границы классификации
h = 0.02

x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

xx, yy = np.meshgrid(
    np.arange(x_min, x_max, h),
    np.arange(y_min, y_max, h)
)

grid = np.c_[xx.ravel(), yy.ravel()]
grid_tensor = torch.FloatTensor(grid)

with torch.no_grad():
    grid_predictions = model(grid_tensor)
    Z = torch.argmax(grid_predictions, dim=1)

Z = Z.numpy().reshape(xx.shape)

plt.figure(figsize=(10, 8))

plt.contourf(xx, yy, Z, alpha=0.3, cmap=plt.cm.rainbow)

plt.scatter(
    X[:, 0],
    X[:, 1],
    c=y,
    cmap=plt.cm.rainbow,
    edgecolors="black",
    s=40
)

plt.title("Decision boundaries of improved MLP")
plt.xlabel("x1")
plt.ylabel("x2")
plt.show()

Epoch    0 | Loss = 1.1110 | Accuracy = 0.3333
Epoch  200 | Loss = 0.1174 | Accuracy = 0.9567
Epoch  400 | Loss = 0.0460 | Accuracy = 0.9900
Epoch  600 | Loss = 0.0439 | Accuracy = 0.9833
Epoch  800 | Loss = 0.0327 | Accuracy = 0.9833
Epoch 1000 | Loss = 0.0192 | Accuracy = 0.9933
Epoch 1200 | Loss = 0.0151 | Accuracy = 0.9967
Epoch 1400 | Loss = 0.0199 | Accuracy = 0.9900
Epoch 1600 | Loss = 0.0216 | Accuracy = 0.9933
Epoch 1800 | Loss = 0.0200 | Accuracy = 0.9933
Epoch 2000 | Loss = 0.0200 | Accuracy = 0.9900
Epoch 2200 | Loss = 0.0174 | Accuracy = 0.9933
Epoch 2400 | Loss = 0.0125 | Accuracy = 0.9967


KeyboardInterrupt: 